### ISSUE TITLE
Enlever la déclaration globale de ServerName

### ISSUE THREAD

**Issue by Xwaler** [Warroller808/AppMichelet#1]
Le soucis original: des requêtes destinées à des FQN étrangers arrivent jusqu'à Django, ce qui indique que apache ne filtre pas. C'est pour sûr du au fait que le site par 000-default a été désactivé donc le default_server de fallback est AppMichelet. C'est critique niveau sécurité.

Ce qui a été essayé: réactiver le 000-default et y rajouter un "ServerName catchall" de ce que j'ai compris ?
Si le ServerName a été ajouté de façon globale çad à l'extérieur du bloc VirtualHost, c'est tout a fait possible que ça provoque les erreurs 500. Le soucis du ServerName en dehors du bloc est que lorsque apache collecte les sites, il va basiquement concaténer les fichiers de conf des sites, donc le ServerName écrasera celui de AppMichelet, ou l'inverse selon la météo ^^

Ensuite je crois que tu as essayé en laissant 000-default activé mais sans y ajouter de ServerName, donc la conf par défaut nature ? Et ça cassait le https. Ca c'est à cause du fait que le ServerName est défini globalement dans AppMichelet.conf aussi. J'ai reproduit la conf sur une machine test et ça donne ça :

![image](https://github.com/Warroller808/AppMichelet/assets/35381919/74d1b20e-dbee-4c2d-acda-8fe3fdbc80e8)

Tu peux voir que le 000-default chope le ServerName !! Donc quand les requêtes arrivent, le 000-default match sur le ServerName et c'est ce site qui est chargé à la place de celui de django, hors il ne possède pas ton certificat https donc ça foire complet.

En passant le ServerName dans le VirtualHost, on récupère une config clean avec un defaut_server qui n'interceptera pas de requêtes destinées à django.

![image](https://github.com/Warroller808/AppMichelet/assets/35381919/de0c480f-fbe3-4d06-b8bb-a2bf137984d3)

Donc je suis plutôt confiant qu'en modifiant ça ça devrait enfin fonctionner comme prévu :

```diff
echo "
-ServerName controle-remises.appmichelet.ovh

WSGIDaemonProcess AppMichelet processes=4 python-home=/var/www/AppMichelet/venv python-path=/var/www/AppMichelet
WSGIProcessGroup AppMichelet
WSGIScriptAlias / /var/www/AppMichelet/AppMichelet/wsgi.py

<VirtualHost *:80>
+   ServerName controle-remises.appmichelet.ovh
+
    ErrorLog \${APACHE_LOG_DIR}/AppMichelet-error.log
    CustomLog \${APACHE_LOG_DIR}/AppMichelet-access.log combined

    Alias /robots.txt /var/www/AppMichelet/static/robots.txt
    Alias /favicon.ico /var/www/AppMichelet/static/favicon.ico
    Alias /static/ /var/www/AppMichelet/static/
    Alias /media/ /var/www/AppMichelet/media/

    <Directory /var/www/AppMichelet/AppMichelet>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    <Directory /var/www/AppMichelet/static>
        Require all granted
    </Directory>

    <Directory /var/www/AppMichelet/media>
        Require all granted
    </Directory>
</VirtualHost>
" > /etc/apache2/sites-available/AppMichelet.conf

-a2dissite 000-default.conf
a2ensite AppMichelet

certbot --apache -d "controle-remises.appmichelet.ovh"
```

**Comment by Warroller808** [comment]
Top ça s'éclaircit merci !
Je teste ça demain.
Pour info le catchall était dans le virtualhost, pas à l'extérieur dans les fichiers default.
L'idée serait donc de déplacer le ServerName des deux fichiers AppMichelet.conf et AppMichelet-le-ssl.conf, et réactiver 000-default.conf et default-ssl.conf sans le catchall ?

**Comment by Xwaler** [comment]
> Pour info le catchall était dans le virtualhost, pas à l'extérieur dans les fichiers default.

Oh, donc j'ai un peu plus creusé et j'ai trouvé un autre soucis :P

De la même manière, on défini WSGIScriptAlias de façon globale, c'est ça qui permet de dire que toutes les requêtes ayant un chemin préfixé par "/" (donc toutes) doivent être servies à travers l'application WSGI de ton application Django. C'est équivalent à avoir un bloc <Location /> dans le VirtualHost qui redirige vers l'app Django. Sauf que du coup c'est aussi appliqué à 000-default donc toutes les requêtes qui arrivent dans le default_server sont à priori tout de même envoyée à Django, yikes!

Ca explique donc pourquoi tu avais encore des requêtes qui passaient lors de ton premier essai.

Donc il faut déplacer le WSGIProcessGroup et WSGIScriptAlias dans le vhost, WSGIDaemonProcess doit rester global car sinon il sera déclaré dans deux vhost (vu que AppMichelet-le-ssl est une copie de AppMichelet) et apache n'aime vraiment pas ça. J'ai juste trouvé un gist qui fait ça comme ça, pas beaucoup de documentation malheureusement. https://gist.github.com/gustavosouzalima/5794838

---

Ensuite il ne faut réactiver que 000-default, default-ssl.conf est un exemple de conf SSL non fonctionnel et il n'est pas activé par défaut. Il n'y en a pas besoin dans le cadre du SSL car le certificat est déjà lié exclusivement au domaine, si le domaine ne match pas Apache renvoie directement une réponse [495](https://fr.wikipedia.org/wiki/Liste_des_codes_HTTP#4xx_-_Erreur_du_client_HTTP:~:text=ferm%C3%A9%20la%20connexion.-,495,-SSL%20Certificate%20Error).

---

Putting it all together :

```diff
echo "
-ServerName controle-remises.appmichelet.ovh

WSGIDaemonProcess AppMichelet processes=4 python-home=/var/www/AppMichelet/venv python-path=/var/www/AppMichelet
-WSGIProcessGroup AppMichelet
-WSGIScriptAlias / /var/www/AppMichelet/AppMichelet/wsgi.py

<VirtualHost *:80>
+   ServerName controle-remises.appmichelet.ovh
+
+   WSGIProcessGroup AppMichelet
+   WSGIScriptAlias / /var/www/AppMichelet/AppMichelet/wsgi.py
+
    ErrorLog \${APACHE_LOG_DIR}/AppMichelet-error.log
    CustomLog \${APACHE_LOG_DIR}/AppMichelet-access.log combined

    Alias /robots.txt /var/www/AppMichelet/static/robots.txt
    Alias /favicon.ico /var/www/AppMichelet/static/favicon.ico
    Alias /static/ /var/www/AppMichelet/static/
    Alias /media/ /var/www/AppMichelet/media/

    <Directory /var/www/AppMichelet/AppMichelet>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    <Directory /var/www/AppMichelet/static>
        Require all granted
    </Directory>

    <Directory /var/www/AppMichelet/media>
        Require all granted
    </Directory>
</VirtualHost>
" > /etc/apache2/sites-available/AppMichelet.conf

-a2dissite 000-default.conf
a2ensite AppMichelet

certbot --apache -d "controle-remises.appmichelet.ovh"
```

- modifs à appliquer dans les deux conf AppMichelet
- réactiver 000-default seulement

**Comment by Warroller808** [comment]
J'ai fait les modifications. Maintenant l'url / du site renvoie vers la page par défaut d'ubuntu, et les autres pages renvoient des erreurs 404.
Voici la conf actuelle :
![image](https://github.com/Warroller808/AppMichelet/assets/63857105/ac668666-bc77-4519-8d83-42deb76d3ca9)

Et voici les fichiers :

000-default.conf
```
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>
```

AppMichelet.conf
```
WSGIDaemonProcess AppMichelet processes=4 python-home=/var/www/AppMichelet/venv python-path=/var/www/AppMichelet

<VirtualHost *:80>
    ServerName controle-remises.appmichelet.ovh

    WSGIProcessGroup AppMichelet
    WSGIScriptAlias / /var/www/AppMichelet/AppMichelet/wsgi.py

    ErrorLog ${APACHE_LOG_DIR}/AppMichelet-error.log
    CustomLog ${APACHE_LOG_DIR}/AppMichelet-access.log combined

    Alias /robots.txt /var/www/AppMichelet/static/robots.txt
    Alias /favicon.ico /var/www/AppMichelet/static/favicon.ico
    Alias /static/ /var/www/AppMichelet/static/
    Alias /media/ /var/www/AppMichelet/media/

    <Directory /var/www/AppMichelet/AppMichelet>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    <Directory /var/www/AppMichelet/static>
        Require all granted
    </Directory>

    <Directory /var/www/AppMichelet/media>
        Require all granted
    </Directory>

    RewriteEngine on
    RewriteCond %{SERVER_NAME} =controle-remises.appmichelet.ovh
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

AppMichelet-le-ssl.conf
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ErrorLog ${APACHE_LOG_DIR}/AppMichelet-error.log
    CustomLog ${APACHE_LOG_DIR}/AppMichelet-access.log combined

    Alias /robots.txt /var/www/AppMichelet/static/robots.txt
    Alias /favicon.ico /var/www/AppMichelet/static/favicon.ico
    Alias /static/ /var/www/AppMichelet/static/
    Alias /media/ /var/www/AppMichelet/media/

    <Directory /var/www/AppMichelet/AppMichelet>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    <Directory /var/www/AppMichelet/static>
        Require all granted
    </Directory>

    <Directory /var/www/AppMichelet/media>
        Require all granted
    </Directory>

    ServerName controle-remises.appmichelet.ovh
    SSLCertificateFile /etc/letsencrypt/live/controle-remises.appmichelet.ovh/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/controle-remises.appmichelet.ovh/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    LogLevel error
</VirtualHost>
</IfModule>
```

**Comment by Warroller808** [comment]
Problème résolu, je n'avais pas la config WSGI dans AppMichelet-le-ssl.conf, vu qu'elle n'était plus déclarée en global. Donc je l'ai ajoutée et le site est de nouveau accessible.
Je surveille les logs Django.

**Comment by Warroller808** [comment]
Je n'ai bien que ton attaque de ce midi dans les logs, depuis plus rien, ça semble résolu ! Merci beaucoup maintenant je comprends la conf Apache ! ;)

**Comment by Xwaler** [comment]
Top ! Avec plaisir ;) on a tous les deux pas mal appris avec cette histoire :P
